version: '3'
services:
  postgresql:
    container_name: postgresql
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kenkoooo
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - ../config/database-definition.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    container_name: atcoder-problems-redis
    image: redis:6.0.9
    ports:
      - "6379:6379"

  api_server:
    build: .
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      SQL_URL: postgres://kenkoooo:pass@postgresql:5432/test
      CLIENT_ID: a
      CLIENT_SECRET: b
    command: run_server
    links:
      - "postgresql"
